apiVersion: v1
kind: Service
metadata:
  name: testdeploymentservice
spec:
  selector:
    app.kubernetes.io/name: testn_deploymentpod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80