apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-api
  template:
    metadata:
      labels:
        app: my-web-api
    spec:
      containers:
      - name: my-web-api
        image: your_dockerhub_username/mywebapp:latest
        ports:
        - containerPort: 8080