apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: ca-test-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapi
  template:
    metadata:
      labels:
        app: ca-test-demo
        service: webapi
    spec:
      containers:
        - name: webapicontainer
          image: ca-test-demo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
