apiVersion: v1
kind: Service
metadata:
  name: webapiservice
  labels:
    app: ca-test-demo
    service: webapi
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
  selector:
    service: webapi
